version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nextjs-app
    exclude:
      - appspec.yml
      - scripts/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_pm2.sh
      timeout: 300
      runas: ec2-user
#  ValidateService:
#    - location: scripts/validate.sh
#      timeout: 300
#      runas: ec2-user
